# roles/rawx/tasks/offline.yml
---
- name: offline - Reset defaults
  set_fact:
    _openio_rawx_servicename: "{{ rx.ansible_facts._rawx.name }}"
    _openio_rawx_bind_port: "{{ rx.ansible_facts._rawx.port }}"
    _openio_rawx_serviceid: "{{ rx.ansible_facts._rawx.id }}"
    _openio_rawx_volume: "{{ rx.ansible_facts._rawx.volume }}"
    _openio_rawx_state: "{{ rx.ansible_facts._rawx.state }}"
  tags:
    - install
    - configure

- name: offline - Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0640
  with_items:
    - src: "gridinit_rawx.conf.j2"
      dest: "{{ openio_rawx_gridinit_dir }}/{{ openio_rawx_gridinit_file_prefix }}\
        {{ _openio_rawx_servicename }}.conf"
  register: _rawx_conf
  tags: configure

- block:
    - name: offline - stop rawx to apply the new configuration
      shell: gridinit_cmd stop  {{ openio_rawx_namespace }}-{{ _openio_rawx_servicename }}

    - name: offline - Set properties
      set_fact:
        need_reload: true
  when:
    - _rawx_conf is changed
    - not openio_rawx_provision_only
  tags: configure
...
