# roles/rawx/tasks/present.yml
---

- name: present - Reset defaults
  set_fact:
    _openio_rawx_servicename: "{{ rx.ansible_facts._rawx.name }}"
    _openio_rawx_bind_port: "{{ rx.ansible_facts._rawx.port }}"
    _openio_rawx_serviceid: "{{ rx.ansible_facts._rawx.id }}"
    _openio_rawx_volume: "{{ rx.ansible_facts._rawx.volume }}"
    _openio_rawx_state: "{{ rx.ansible_facts._rawx.state }}"
    _openio_rawx_location: "{{ openio_location_room | default ('') }}{{ openio_location_rack | default ('') }}\
  {{ openio_location_server | default (ansible_hostname ~ '.') }}{{ rx.ansible_facts._rawx.id }}"
  tags:
    - install
    - configure

- name: present - Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "{{ _openio_rawx_volume }}"
    - path: "{{ openio_rawx_sysconfig_dir }}/{{ _openio_rawx_servicename }}"
    - path: "/var/log/oio/sds/{{ openio_rawx_namespace }}/{{ _openio_rawx_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0770"
  tags: install

- name: present - Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0640
  with_items:
    - src: "rawx.conf.j2"
      dest: "{{ openio_rawx_sysconfig_dir }}/\
        {{ _openio_rawx_servicename }}/{{ _openio_rawx_servicename }}-httpd.conf"
    - src: "gridinit_rawx.conf.j2"
      dest: "{{ openio_rawx_gridinit_dir }}/{{ openio_rawx_gridinit_file_prefix }}\
        {{ _openio_rawx_servicename }}.conf"
    - src: "watch-rawx.yml.j2"
      dest: "{{ openio_rawx_sysconfig_dir }}/watch/{{ _openio_rawx_servicename }}.yml"
  register: _rawx_conf
  tags: configure

- block:
    - name: present - Set properties
      set_fact:
        need_reload: true
  when:
    - _rawx_conf is changed
    - not openio_rawx_provision_only
  tags: configure
...
